exports.isValidYouTubeUrl = (url) => {
  return /^(https?:\/\/)?(www\.)?(youtube\.com|youtu\.be)\//.test(url);
};

/**
 * True when the URL points at a whole playlist (no single video selected).
 * Playlists cannot be delivered as one HTTP response, so the stream endpoint
 * rejects them with a clear message instead of producing a broken file.
 */
exports.isPlaylistUrl = (url) => {
  const hasList = /[?&]list=/.test(url);
  const hasVideo = /[?&]v=/.test(url) || /youtu\.be\//.test(url) || /\/shorts\//.test(url);
  return hasList && !hasVideo;
};

const FORMAT_ALLOWED_CHARS = /^[A-Za-z0-9_+\[\]<>=:,.!*\/~\-\s]+$/;

/**
 * Format selectors are passed straight to `yt-dlp -f`, so they must be
 * restricted to the small character set yt-dlp selectors actually use.
 * Anything that could be parsed as a second CLI flag is rejected.
 */
exports.isValidFormatSelector = (format) => {
  if (typeof format !== "string") return false;
  const value = format.trim();
  if (!value || value.length > 120) return false;
  if (value.startsWith("-") || value.includes("--")) return false;
  if (!FORMAT_ALLOWED_CHARS.test(value)) return false;
  return true;
};

/**
 * Job ids are generated by the browser so it can subscribe to progress events
 * before the download request is answered.
 */
exports.isValidJobId = (jobId) => {
  return typeof jobId === "string" && /^[0-9a-fA-F-]{8,64}$/.test(jobId);
};

/**
 * Turn a video title into a filename that is safe on Windows/macOS/Linux and
 * safe to put inside an HTTP header.
 */
exports.toSafeFilename = (title, fallback = "video") => {
  const cleaned = String(title || "")
    .replace(/[<>:"/\\|?*\x00-\x1f]/g, "_")
    .replace(/\s+/g, " ")
    .trim()
    .substring(0, 150)
    .replace(/[. ]+$/, "");
  return cleaned || fallback;
};
